services:
  server:
    build:
      context: .
    environment:
      NODE_ENV: production
      DB_PASSWORD: "YOUR_ACTUAL_MARIADB_ROOT_PASSWORD_HERE" # Put your DB password here
    ports:
      - "5000:5000"
    networks:
      - etodo_network

networks:
  etodo_network:
    external: true
    name: portainer_default # Replace this with whatever network name your main mariadb container is using!