services:
  server:
    build:
      context: .
    container_name: etodo-server
    restart: always
    environment:
      NODE_ENV: production
      DB_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5000:5000"
    networks:
      - default # This tells Docker to use the bridge network

networks:
  default:
    external: true
    name: bridge